Updates to incorporate other data sources
ubccr/xdmod-supremm pull request #346
Opened 2023-08-30 15:10 UTC by connersaeli

This change to the default dataset mapping file allows for other datasource names to be populated in the datasource column.

## Description

- These changes and the corresponding changes in https://github.com/ubccr/supremm/pull/259 populate the "summarization" field of the mongo record with the "datasource" defined in the Python-based supremm software's resource configuration. If the "summarization.datasource" field is not present, then the record must have been generated from PCP data.
- Linked pcp.js to supremm.js for backward compatability

## Motivation and Context
Depends on these changes to the Python-based supremm software: https://github.com/ubccr/supremm/pull/259

## Tests performed

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project as found in the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-08-30 20:06 UTC, jpwhite4 commented on etl/js/config/supremm/tests/pcp/input/9012345-1693433245.json
> +		"srcdir" : None,
This file is not valid json.

2023-08-31 13:32 UTC, jpwhite4 commented
The plan is to have the dataset mapping check for the presence of the summarization.datasource value and (if it exists) use that.
Please can you revert the code changes to that version.

2023-08-31 13:38 UTC, jpwhite4 requested changes
Please make a pull request that generates the datasource value from the summary data (like you had yesterday).

2023-08-31 14:24 UTC, connersaeli commented on etl/js/config/supremm/tests/pcp/input/9012345-1693433245.json
> +		"srcdir" : None,
Resolved in [4effff5](https://github.com/ubccr/xdmod-supremm/pull/346/commits/4effff5fc58aa1fdfabd8adc69a951563d94de2c)

2023-08-31 19:59 UTC, jpwhite4 commented on etl/js/config/supremm/tests/pcp/input/8291026-1518721536.json
> +                "submit" : 1518721453,
please avoid making changes to whitespace in lines that don't otherwise change - it makes it more difficult to review, you'll get dinged by the linter and it messes up the git blame

2023-08-31 19:59 UTC, jpwhite4 commented on etl/js/config/supremm/dataset_maps/pcp.js
> +                        return { value: this.ref(job, 'summarization.datasource'), error: 0 };
```suggestion
                        return this.ref(job, 'summarization.datasource');
```

2023-09-06 16:50 UTC, connersaeli commented on etl/js/config/supremm/dataset_maps/pcp.js
> +                        return { value: this.ref(job, 'summarization.datasource'), error: 0 };
Resolved in https://github.com/ubccr/xdmod-supremm/pull/346/commits/24e0143023862503f8951081dccf355d88477fbe

2023-09-06 16:50 UTC, connersaeli commented on etl/js/config/supremm/tests/pcp/input/8291026-1518721536.json
> +                "submit" : 1518721453,
Resolved in https://github.com/ubccr/xdmod-supremm/pull/346/commits/3fca4ab646fda447b32055397d8a704508ff91a1

2023-09-06 17:51 UTC, jpwhite4 commented
1) git mv pcp.js to supremm.js
2) ln -ssupremm.js  pcp.js ; git add pcp.js
3) add tests to check both dataset mapping files function

2023-09-06 21:34 UTC, jpwhite4 approved these changes

2023-09-07 14:29 UTC, merged