Sanitize NAN values from timeseries data
ubccr/xdmod-supremm pull request #353
Opened 2023-09-25 18:34 UTC by aestoltm

## Description

Add check to sanitize job timeseries data of NAN values due to Symfony throwing double NAN error when json encoding. Added helper function which replaces any NAN values in the series data with 0.

Original PR for this issue: https://github.com/ubccr/xdmod/pull/1778 

## Motivation and Context

Charts with NAN data would return a null record.

## Tests performed

Observed changes on xdmod-dev

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project as found in the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-09-25 19:24 UTC, aaronweeden requested changes
Can you please explain an example of how to reproduce the problem in the "Motivation and Context" section and explain in more detail how you tested it on xdmod-dev in the "Tests performed" section?

Without being sure how to reproduce the error, I'm not sure yet if changing NaN to zero is the right solution.

2023-09-25 19:24 UTC, aaronweeden commented on classes/DataWarehouse/Query/SUPREMM/JobMetadata.php
> +    {
I would add a docblock comment above this new method explaining what it does and with explanations of the `@param` and `@return`.

2023-09-25 19:24 UTC, aaronweeden commented on classes/DataWarehouse/Query/SUPREMM/JobMetadata.php
> +        $this->sanitize($doc);
I would change the method from passing by reference to returning a changed copy of the object so this method call is more readable; otherwise, at first glance, it isn't clear that `$doc` is being changed here.
Also, if it's static, it should use `self::` not `$this->`.

2023-09-25 19:24 UTC, aaronweeden commented on classes/DataWarehouse/Query/SUPREMM/JobMetadata.php
> +            }
```suggestion
            elseif (is_numeric($val) && is_nan($val)) {
                $doc[$key] = 0;
            }
```

2024-05-23 19:36 UTC, jpwhite4 approved these changes

2024-05-28 22:16 UTC, aaronweeden commented
Looks like the PR description should be updated to say it replaces them with null instead of 0.

2024-05-29 15:06 UTC, aestoltm commented
> Looks like the PR description should be updated to say it replaces them with null instead of 0.

Updated the description that the value is relpaced with `null`

2024-05-30 14:55 UTC, aaronweeden approved these changes

2024-05-30 15:01 UTC, merged