Add docs for application.json customization.
ubccr/xdmod-supremm pull request #378
Opened 2024-05-23 16:45 UTC by jpwhite4

Add description about how to customize the application identification algorithm.

2024-05-23 19:49 UTC, aaronweeden requested changes

2024-05-23 19:49 UTC, aaronweeden commented on docs/customization.md
> +application. The applications are processed in order and the match with the highest
```suggestion
application. The applications are processed in the order they appear in the file, and the match with the highest
```

2024-05-23 19:49 UTC, aaronweeden commented on docs/customization.md
> +priority is used. If no match is found then the application is assigned
What does `priority` mean in this context?

2024-05-23 19:49 UTC, aaronweeden commented on docs/customization.md
> +executable paths. If an executable matches then the job is assigned the corresponding
```suggestion
executable (i.e., the executable path with the leading directory components removed). If an executable matches, then the job is assigned the corresponding
```

2024-05-23 19:49 UTC, aaronweeden commented on docs/customization.md
> +directory components removed).
```suggestion
that are tested against the executable.
```

2024-05-23 19:49 UTC, aaronweeden commented on docs/customization.md
> +| hints     | deprecated | Deprecated do not use |
```suggestion
| `name`  | [String] | The name of the application &mdash; this must be unique. |
| `license_type` | `permissive` \| `proprietary` | Information about the software license. If the software has a license that restricts publishing of performance data, then set this field to <code>proprietary</code>; otherwise, <code>permissive</code> should be used. The application names for <code>proprietary</code> licensed code do not appear in the XDMoD portal. |
| `science_area` | [String] | The science area of the application. This information is stored in the XDMoD data warehouse, but is not displayed in the portal. |
| `url`  | [String] | The website of the application. This information is stored in the XDMoD data warehouse, but is not displayed in the portal. It is intended to assist developers in disambiguating software applications that have similar names. |
| `execmatch` | OPTIONAL LIST | Optional list of regular expressions that will be checked against the executable (i.e., the executable path with the leading directory components removed). |
| `pathmatch` | OPTIONAL LIST | Optional list of regular expressions that will be checked against the executable path. |
| `hints`     | deprecated | Deprecated, do not use. |
```

2024-05-23 19:49 UTC, aaronweeden commented on docs/customization.md
> +into the XDMoD datawarehouse).  The application lookup regular expressions
```suggestion
into the XDMoD data warehouse).  The application lookup regular expressions
```

2024-05-23 19:49 UTC, aaronweeden commented on docs/customization.md
> +priority is used. If no match is found then the application is assigned
```suggestion
priority is used. If no match is found, then the application is assigned
```

2024-05-23 19:49 UTC, aaronweeden commented on docs/customization.md
> +to 'uncategorized'. If no executable path information is available then the
```suggestion
to 'uncategorized'. If no executable path information is available, then the
```

2024-05-23 19:49 UTC, aaronweeden commented on docs/customization.md
> +the new definition has been added then the database dimension tables
```suggestion
the new definition has been added, then the database dimension tables
```

2024-05-23 19:49 UTC, aaronweeden commented on docs/customization.md
> +must be updated as follows:
```suggestion
must be updated as follows (Note: depending on how you installed XDMoD, `/usr/share/xdmod` should be replaced with `/opt/xdmod/share` or the correct path to the `share` directory, and `/etc/xdmod` should be replaced with `/opt/xdmod/etc` or the correct path to the `etc` directory).
```

2024-05-23 19:49 UTC, aaronweeden commented on docs/customization.md
> +node etl.cli.js -o > /etc/xdmod/etl/etl_sql.d/supremm/application.sql
```suggestion
# cd /usr/share/xdmod/etl/js
# node etl.cli.js -o > /etc/xdmod/etl/etl_sql.d/supremm/application.sql
```

2024-05-23 19:49 UTC, aaronweeden commented on docs/customization.md
> +to include the `-d` debug flag so that you can monitor the progress.
````suggestion
After updating the tables, run the `aggregate_supremm.sh` script to reaggregate the data. The script will automatically detect which time periods need to be
reaggregated. The amount of time the script will take to run depends on the number of time periods
that need to be reaggregated. It is recommended to run the script in a `screen` or `tmux` session and
to include the `-d` debug flag so that you can monitor the progress:
```
# aggregate_supremm.sh -d
```
````

2024-05-29 18:30 UTC, jpwhite4 commented on docs/customization.md
> +relative location in the file.  If the relative order of applications changes
No because when we add new applications  in a future release then the ones they added need to be in the same relative location. If their custom ones get put at the end then the primary keys will be wrong.

2024-05-29 18:34 UTC, jpwhite4 commented on docs/customization.md
> +priority is used. If no match is found then the application is assigned
say you have two executables that ran:  `apples.exe` and `oranges.exe` and imagine that the community application A is associated with apples.exe and community application O is associated with oranges.exe. The application that is tagged for the job will be the one that appears first in the definition file.

2024-06-17 20:47 UTC, aaronweeden commented on docs/customization.md
> +priority is used. If no match is found, then the application is assigned
```suggestion
priority (i.e., that appears first in the file) is used. If no match is found, then the application is assigned
```

2024-06-17 20:51 UTC, aaronweeden commented on docs/customization.md
> +mapping extending guide).
```suggestion
Instructions for reseting and re-ingesting data are in [Section 4 of the data
mapping extending guide](extending.md#4-re-ingest-data-into-xdmod).
```

2024-06-17 20:53 UTC, aaronweeden commented on docs/customization.md
> +that were previously uncategorized and had a executable of 'nexmd.exe':
```suggestion
that were previously uncategorized and had an executable of `nexmd.exe`:
```

2024-06-17 21:06 UTC, aaronweeden commented on docs/customization.md
> +at your site, then remove the regular expression definitions that cause
```suggestion
all data. If there is an existing job entry that you don't want to match,
then remove the regular expression definitions that cause
```

2024-06-17 21:07 UTC, aaronweeden commented on docs/customization.md
> +all data. If there is an existing job entry that you don't want to match
should that be `application entry` instead of `job entry`?

2024-06-17 21:24 UTC, aaronweeden commented on docs/customization.md
> +all data.
```suggestion
If you do edit `application.json`, you will need to re-apply those edits every time
you upgrade the XDMoD software. When it comes time to upgrade:
1. Back up your edits to `application.json`.
1. Install the new version of XDMoD but don't run `xdmod-upgrade` yet.
1. Re-apply your edits to `application.json`, but make sure any applications you previously added appear *before* any new applications that were added by the installation. Otherwise, if the relative order of applications is different, then it would cause the database primary keys to change and would necessitate a complete deletion and reingestion of all data.
1. After you have re-applied your edits, run the `etl.cli.js -o` command mentioned earlier.
1. Finally, run the `xdmod-upgrade` command.
```

2024-08-28 21:09 UTC, aaronweeden requested changes

2024-08-28 21:09 UTC, aaronweeden commented on docs/customization.md
> +This list of applications is maintained in the `share` directory (whose location depends on how you installed XDMoD, e.g., `/usr/share/xdmod`, `/opt/xdmod/share`) under `etl/js/config/supremm/applica
```suggestion
This list of applications is maintained in the `share` directory (whose location depends on how you installed XDMoD, e.g., `/usr/share/xdmod`, `/opt/xdmod/share`) under `etl/js/config/supremm/application.json`.
```

2024-09-10 19:05 UTC, merged