Add changelog for xdmod11.0
ubccr/xdmod-supremm pull request #385
Opened 2024-07-12 21:07 UTC by jpwhite4

2024-08-27 19:46 UTC, aaronweeden requested changes

2024-08-27 19:46 UTC, aaronweeden commented on CHANGELOG.md
> +- Misc
```suggestion
- Miscellaneous
```

2024-08-27 19:46 UTC, aaronweeden commented on CHANGELOG.md
> +    - Refactor test namespaces and replace redundant exception classes with ones provided by Symfony. ([\#355](https://github.com/ubccr/xdmod-supremm/pull/355))
```suggestion
    - Replace redundant exception classes with ones provided by Symfony. ([\#355](https://github.com/ubccr/xdmod-supremm/pull/355))
```

2024-08-27 19:46 UTC, aaronweeden commented on CHANGELOG.md
> +    - Update jsPlumb dependency. ([\#372](https://github.com/ubccr/xdmod-supremm/pull/372))
```suggestion
    - Update jsPlumb dependency. ([\#372](https://github.com/ubccr/xdmod-supremm/pull/372))
    - Refactor job data set analysis fields ([\#256](https://github.com/ubccr/xdmod-supremm/pull/256))
```

2024-08-28 15:55 UTC, aaronweeden commented on CHANGELOG.md
> +    - Add LEAST() function to SQL that gets the `wall_time_accuracy` value. ([\#324](https://github.com/ubccr/xdmod-supremm/pull/324))
```suggestion
    - Add `LEAST()` function to SQL that gets the `wall_time_accuracy` value. ([\#324](https://github.com/ubccr/xdmod-supremm/pull/324))
```

2024-08-28 15:57 UTC, aaronweeden commented on CHANGELOG.md
> +    - Various CI test updates ([\#369](https://github.com/ubccr/xdmod-supremm/pull/369), [\#381](https://github.com/ubccr/xdmod-supremm/pull/381), [\#350](https://github.com/ubccr/xdmod-supremm/pull/
`xdmod` and the other modules don't list the PRs that change CI tests. Should they, or should this line be removed?

2024-09-04 13:39 UTC, jpwhite4 commented on CHANGELOG.md
> +    - Various CI test updates ([\#369](https://github.com/ubccr/xdmod-supremm/pull/369), [\#381](https://github.com/ubccr/xdmod-supremm/pull/381), [\#350](https://github.com/ubccr/xdmod-supremm/pull/
My thought is that the CHANGELOG.md is information for developers and the .html changelog is for end-users. Hence including the ci updates in the .md version

2024-09-10 18:42 UTC, merged